version: '3.2'
services:
  plugin:
    image: quay.io/arcalot/arcaflow-plugin-rtla
    build: .
    volumes:
      - source: ./configs/timerlat_example.yaml
        target: /config/example.yaml
        type: bind
